### ISSUE TITLE
Py error: No JSON object could be decoded

### ISSUE THREAD

**Issue by pcav** [geobricks/geobricks_qgis_plugin_faostat#2]
When selecting indicators, I got:

Traceback (most recent call last):
  File "/home/paolo/.qgis2/python/plugins/geobricks_qgis_plugin_faostat/geobricks_qgis_plugin_faostat.py", line 314, in on_domain_change
    elements = get_elements(domain_code)
  File "/home/paolo/.qgis2/python/plugins/geobricks_qgis_plugin_faostat/geobricks_faostat_connector.py", line 32, in get_elements
    elements = json.loads(json_data)['data']
  File "/usr/lib/python2.7/json/**init**.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Versione Python:
2.7.10+ (default, Oct 10 2015, 09:11:24) 
[GCC 5.2.1 20151028]

Versione di QGIS:
2.8.3-Wien Wien, exported

**Comment by Kalimaha** [comment]
Can I ask you for what group/domain selection does it happen? Many thanks.

**Comment by pcav** [comment]
Food Security > Indicators from Household Surveys (gender etc.
